#version: '3.3'
services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
#    volumes:
#      - static_value:/app/static/
#      - media_value:/app/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  db:
    image: postgres:16-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine
    restart: always

  nginx:
    image: nginx:1.26.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/:/usr/share/nginx/html/
#      - static_value:/var/html/static/
#      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
#  static_value:
#  media_value:
  db_value: